steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim \
    --token "PaN4D5k3eSRf1zS2JO3dVtDjvlGEopn9GUlJNhWcgLKRyZiJlt" \
    --project "smOvat6DJ6lmfoLjEsMX" \
    --grid "Testim-Grid" \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  displayName: 'publish testim test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml'